### ISSUE TITLE
How to begin using angular responsive images?

### ISSUE THREAD

**Issue by siddhion** [c0bra/angular-responsive-images#1]
When I download `angular-responsive-images-master` and extract it I see I have all these files:

```
~/Desktop/angular-responsive-images-master$ tree
.
├── bower.json
├── Gruntfile.js
├── package.json
├── README.md
├── src
│   └── ng-responsive-images.js
└── test
    ├── config
    │   └── karma.conf.js
    ├── lib
    │   ├── angular.js
    │   └── angular-mocks.js
    └── unit
        └── ng-responsive-images.spec.js
```

How do I begin using it? Should I just drop `ng-responsive-images.js` in my AngularJS app's `scripts` folder and include it along with AngularJS in my `index.html` file? Or is there more complicated configuring that needs to be done?

**Comment by c0bra** [comment]
Adam,

The project is still mostly alpha, so I don't have versioned downloads or
anything yet.

For now, I've added download/reference links to rawgithub.com on the
readme. Here's a link:
https://github.com/c0bra/angular-responsive-images#download--reference

Hope that helps!

Brian

**Comment by siddhion** [comment]
Ahh ok. Thanks. Yeah I downloaded the minified version, just linked to it in my `index.html`, wrote the code and it works. Thanks!
