### ISSUE TITLE
[Question] How to swap sets of responsive images on view change using ui-router

### ISSUE THREAD

**Issue by NinjaBanjo** [c0bra/angular-responsive-images#3]
Is there a way to swap responsive image sets on route change?

Would be helpful if there is as I am working on a project that could use this badly.
- Thanks

**Comment by mikemclin** [comment]
You can use a value from an parent controller (not the controller that is being replaced by the router) to populate your `bh-src-responsive` attribute.  Then add a listener to update that value on route change.

Something like this...

``` js
// Assuming your app module has been saved to the app variable
app.controller('AppCtrl', function($scope){
  $scope.$on('$routeChangeStart', function(next, current) { 
    // Update your image set
    $scope.responsiveSettings = [ [ '(min-width: 960px)', 'larger_image.jpg' ], [ '(min-width: 1700px)', 'much_larger_image.jpg' ] ];
  });
});
```

``` html
<img src="small_image.jpg" bh-src-responsive="responsiveSettings" />
```

I haven't tested or used this code...  I am just giving an example of how you could potentially set this up.  Hope this gets you on the right track.

**Comment by c0bra** [comment]
That seems like the way to go. Closing as there's been no updates.
