### ISSUE TITLE
Initial image isn't restored on resize

### ISSUE THREAD

**Issue by NinjaBanjo** [c0bra/angular-responsive-images#4]
If you load the page in a size not matching any media queries used in the bg-src-responsive directive, then resize up to a matched size (so the image swaps out), and then reduce the size so that no media queries are matched, the image remains at the last matched media query rather than going back to initial src value.

Not sure if this is a "feature" but I would assume that it should return to the original source as none of the media queries are matched.

**Comment by c0bra** [comment]
Good point. Seems like this could be solved by saving the original value of src="", and then defaulting to that with an `else` branch here: https://github.com/c0bra/angular-responsive-images/blob/master/src/bh-responsive-images.js#L88

**Comment by c0bra** [comment]
Looks like this was fixed with 83fc0e9eed6b. Closing but will re-open if there's still problems with it.
