### ISSUE TITLE
Cross Browser

### ISSUE THREAD

**Issue by waltercolindres** [c0bra/angular-responsive-images#8]
More of a question.

What is the cross browser compatibility? I love it so far, but I am not able to check it in IE9 at the moment. 

Also, can I drop in Angular syntax?
bh-src-responsive="[ [ '(min-width: 960px)', '{{image.url}}' ], [ '(min-width: 1700px)', '{{image.url}}' ] ]"

**Comment by c0bra** [comment]
@waltercolindres I have not tested with IE9. You may need the polyfill listed in the readme.

And you shouldn't need to wrap any of the contents of the attribute with braces; it's read and updated using $observe.

**Comment by c0bra** [comment]
Closing for now, but if you run into issues with IE9 I'm happy to investigate.
